# SecureSync AI — Mock Partner Database for Phase 3
# Simulates Swiggy/Zomato Partner ID verification API

import config

MOCK_PARTNERS = {
    # ── Chennai (Zone 4) ──
    # ── Chennai (Zone 1 & 4) ──
    "SW-982341": {
        "name": "Rajan Kumar",
        "platform": "swiggy",
        "zone": "Zone 4",
        "city": "South Chennai",
        "lat": 13.0125,
        "lon": 80.2241,
        "tenure": "March 2023",
        "tenure_months": 36,
        "score": 92,
        "status": "ACTIVE",
        "hourly_rate": 102,
        "weekly_income": 6120,
    },
    "ZM-112233": {
        "name": "Suresh Babu",
        "platform": "zomato",
        "zone": "Zone 1",
        "city": "Central Chennai",
        "lat": 13.0827,
        "lon": 80.2707,
        "tenure": "July 2024",
        "tenure_months": 20,
        "score": 78,
        "status": "ACTIVE",
        "hourly_rate": 98,
        "weekly_income": 5880,
    },
    "SW-223344": {
        "name": "Arun Kumar",
        "platform": "swiggy",
        "zone": "Zone 4",
        "city": "South Chennai",
        "lat": 13.0067,
        "lon": 80.2206,
        "tenure": "January 2024",
        "tenure_months": 26,
        "score": 85,
        "status": "ACTIVE",
        "hourly_rate": 100,
        "weekly_income": 6000,
    },
    "ZM-998877": {
        "name": "Bala Subramanian",
        "platform": "zomato",
        "zone": "Zone 1",
        "city": "Central Chennai",
        "lat": 13.0900,
        "lon": 80.2650,
        "tenure": "June 2022",
        "tenure_months": 45,
        "score": 96,
        "status": "ACTIVE",
        "hourly_rate": 115,
        "weekly_income": 6900,
    },
    # ── Hyderabad (Zone 2) ──
    "ZM-445521": {
        "name": "Amit Verma",
        "platform": "zomato",
        "zone": "Zone 2",
        "city": "Hyderabad",
        "lat": 17.3850,
        "lon": 78.4867,
        "tenure": "January 2024",
        "tenure_months": 26,
        "score": 85,
        "status": "ACTIVE",
        "hourly_rate": 100,
        "weekly_income": 6000,
    },
    "SW-667788": {
        "name": "Priya Reddy",
        "platform": "swiggy",
        "zone": "Zone 2",
        "city": "Hyderabad",
        "lat": 17.3850,
        "lon": 78.4867,
        "tenure": "September 2023",
        "tenure_months": 30,
        "score": 88,
        "status": "ACTIVE",
        "hourly_rate": 105,
        "weekly_income": 6300,
    },
    "SW-776655": {
        "name": "Rahul Rao",
        "platform": "swiggy",
        "zone": "Zone 2",
        "city": "Hyderabad",
        "lat": 17.4448,
        "lon": 78.3498,
        "tenure": "December 2024",
        "tenure_months": 15,
        "score": 74,
        "status": "ACTIVE",
        "hourly_rate": 92,
        "weekly_income": 5520,
    },
    # ── Delhi (Zone 3) ──
    "SW-334455": {
        "name": "Vikram Singh",
        "platform": "swiggy",
        "zone": "Zone 3",
        "city": "Delhi",
        "lat": 28.6139,
        "lon": 77.2090,
        "tenure": "May 2022",
        "tenure_months": 46,
        "score": 94,
        "status": "ACTIVE",
        "hourly_rate": 110,
        "weekly_income": 6600,
    },
    "ZM-556677": {
        "name": "Rakesh Sharma",
        "platform": "zomato",
        "zone": "Zone 3",
        "city": "Delhi",
        "lat": 28.6139,
        "lon": 77.2090,
        "tenure": "February 2025",
        "tenure_months": 13,
        "score": 72,
        "status": "ACTIVE",
        "hourly_rate": 95,
        "weekly_income": 5700,
    },
    "ZM-123456": {
        "name": "Sandeep Kumar",
        "platform": "zomato",
        "zone": "Zone 3",
        "city": "Delhi",
        "lat": 28.5355,
        "lon": 77.3910,
        "tenure": "August 2023",
        "tenure_months": 31,
        "score": 89,
        "status": "ACTIVE",
        "hourly_rate": 105,
        "weekly_income": 6300,
    },
    # ── Mumbai (Zone 5) ──
    "SW-889900": {
        "name": "Deepak Patil",
        "platform": "swiggy",
        "zone": "Zone 5",
        "city": "Mumbai",
        "lat": 19.0760,
        "lon": 72.8777,
        "tenure": "August 2023",
        "tenure_months": 31,
        "score": 90,
        "status": "ACTIVE",
        "hourly_rate": 108,
        "weekly_income": 6480,
    },
    "ZM-101112": {
        "name": "Farhan Sheikh",
        "platform": "zomato",
        "zone": "Zone 5",
        "city": "Mumbai",
        "lat": 19.0760,
        "lon": 72.8777,
        "tenure": "November 2024",
        "tenure_months": 16,
        "score": 80,
        "status": "ACTIVE",
        "hourly_rate": 100,
        "weekly_income": 6000,
    },
    "SW-556644": {
        "name": "Prasad More",
        "platform": "swiggy",
        "zone": "Zone 5",
        "city": "Mumbai",
        "lat": 19.1176,
        "lon": 72.8480,
        "tenure": "May 2024",
        "tenure_months": 22,
        "score": 84,
        "status": "ACTIVE",
        "hourly_rate": 102,
        "weekly_income": 6120,
    },
    # ── Bengaluru (Zone 6) ──
    "SW-131415": {
        "name": "Karthik Gowda",
        "platform": "swiggy",
        "zone": "Zone 6",
        "city": "Bengaluru",
        "lat": 12.9716,
        "lon": 77.5946,
        "tenure": "April 2024",
        "tenure_months": 23,
        "score": 83,
        "status": "ACTIVE",
        "hourly_rate": 104,
        "weekly_income": 6240,
    },
    "ZM-161718": {
        "name": "Naveen Kumar",
        "platform": "zomato",
        "zone": "Zone 6",
        "city": "Bengaluru",
        "lat": 12.9716,
        "lon": 77.5946,
        "tenure": "June 2023",
        "tenure_months": 33,
        "score": 87,
        "status": "ACTIVE",
        "hourly_rate": 102,
        "weekly_income": 6120,
    },
    "ZM-202122": {
        "name": "Vishnu Murthy",
        "platform": "zomato",
        "zone": "Zone 6",
        "city": "Bengaluru",
        "lat": 12.9141,
        "lon": 77.6412,
        "tenure": "January 2025",
        "tenure_months": 14,
        "score": 75,
        "status": "ACTIVE",
        "hourly_rate": 94,
        "weekly_income": 5640,
    },
    "SW-303132": {
        "name": "Siddharth J",
        "platform": "swiggy",
        "zone": "Zone 6",
        "city": "Bengaluru",
        "lat": 13.0285,
        "lon": 77.5891,
        "tenure": "October 2022",
        "tenure_months": 41,
        "score": 97,
        "status": "ACTIVE",
        "hourly_rate": 112,
        "weekly_income": 6720,
    },
}

# Default fallback for unrecognized partner IDs (demo flexibility)
DEFAULT_PARTNER = {
    "name": "Rajan Kumar",
    "platform": "swiggy",
    "zone": "Zone 4",
    "city": "South Chennai",
    "lat": 13.0125,
    "lon": 80.2241,
    "tenure": "March 2023",
    "tenure_months": 36,
    "score": 82,
    "status": "ACTIVE",
    "hourly_rate": 102,
    "weekly_income": 6120,
}


def lookup_partner(partner_id: str, strict_mode: bool | None = None) -> dict | None:
    """Look up a partner by ID. Strict mode rejects unknown IDs."""
    # Exact match
    if partner_id.upper() in MOCK_PARTNERS:
        return MOCK_PARTNERS[partner_id.upper()]
    # Case-insensitive search
    for pid, data in MOCK_PARTNERS.items():
        if pid.lower() == partner_id.lower():
            return data

    strict = config.STRICT_MOCK_PARTNER_IDS if strict_mode is None else strict_mode
    if strict:
        return None

    # Non-strict mode: demo fallback profile
    return DEFAULT_PARTNER
